# Generated by Django 5.0.14 on 2026-04-12 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('cost', models.PositiveIntegerField()),
                ('goal_wpm', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'levels',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('wpm', models.PositiveIntegerField()),
                ('rewarded_credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='levels.level')),
            ],
            options={
                'db_table': 'submits',
                'indexes': [models.Index(fields=['user_id', 'level'], name='idx_submits_user_level')],
            },
        ),
    ]
